name: SignOfTheTimes
author: Chrisbotcom
website: http://chrisbotcom.github.io/SignOfTheTimes/
main: io.github.chrisbotcom.signofthetimes.SignOfTheTimes
version: 0.0.1
commands:
   sott:
      description: SignOfTheTimes plugin.
      permission: sott
      permission-message: You don't have <permission>
      usage: "Type \u00a7c/help <command>\u00a7r for command list.\n\u00a7cType /? sott [command]\u00a7r for specific help.\nVisit \u00a73http://dev.bukkit.org/bukkit-plugins/SignOfTheTimes/ \u00a7rfor detailed help."
   sott add:
      aliases: rem add
      description: Add a reminder.
      permission: reminder
      permission-message: You don't have <permission>
      usage: /<command>
   sott delete:
      aliases: sott del
      description: Delete reminder(s) by id or by player and/or tag.
      permission: reminder
      permission-message: You don't have <permission>
      usage: /<command>
